package com.oceanview.servlet;

// Importing the ReportService which runs stored procedures in the database to generate reports
import com.oceanview.service.ReportService;
// Gson is a Google library that converts Java objects to JSON format
import com.google.gson.Gson;
// JsonObject lets us manually build a JSON response piece by piece
import com.google.gson.JsonObject;
// @WebServlet annotation tells Tomcat what URL this servlet responds to
import javax.servlet.annotation.WebServlet;
// Importing all the HTTP servlet classes we need (HttpServlet, HttpServletRequest, etc.)
import javax.servlet.http.*;
// Importing IOException which is required when we write data to the response
import java.io.IOException;
// Importing LocalDate for handling the start and end date parameters
import java.time.LocalDate;
// Importing List and Map to hold the report data returned from the database
import java.util.List;
import java.util.Map;

/**
 * ReportServlet - This servlet generates business reports for the hotel.
 * IMPORTANT: This is where we check if the user is an admin before allowing access.
 * Only users with the "ADMIN" role can view reports.
 *
 * It supports two types of reports:
 *   1. "occupancy" - Shows how occupied the hotel rooms are over a date range
 *   2. "revenue"   - Shows how much money the hotel earned over a date range
 *
 * The reports are generated by calling stored procedures in the database
 * through the ReportService.
 */
// @WebServlet annotation maps this servlet to the "/api/reports" URL path
@WebServlet("/api/reports")
public class ReportServlet extends HttpServlet {

    // Gson is a Google library that converts Java objects to JSON format
    private final Gson gson = new Gson();

    /**
     * Handles GET requests - generates a report based on the type, start date, and end date.
     * Only admin users are allowed to access this endpoint.
     */
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
        // We set the response type to JSON so the browser knows what format to expect
        resp.setContentType("application/json");
        // Set character encoding to UTF-8 so special characters display correctly
        resp.setCharacterEncoding("UTF-8");

        // ---- Security Check: Only admins can generate reports ----

        // Get the current session (false = don't create a new one if none exists)
        HttpSession session = req.getSession(false);
        // This is where we check if the user is an admin before allowing access
        // If there is no session OR the user's role is not "ADMIN", deny access
        if (session == null || !"ADMIN".equals(session.getAttribute("role"))) {
            resp.setStatus(403);  // 403 = Forbidden (you don't have permission)
            resp.getWriter().write("{\"error\":\"Admin access required\"}");
            return;  // Stop here - non-admin users cannot proceed
        }

        // ---- Read the report parameters from the request ----

        // Get the report type (either "occupancy" or "revenue")
        String reportType = req.getParameter("type");
        // Get the start date for the report period (e.g., "2025-01-01")
        String startDateStr = req.getParameter("startDate");
        // Get the end date for the report period (e.g., "2025-06-30")
        String endDateStr = req.getParameter("endDate");

        // Check that all three required parameters were provided
        if (reportType == null || startDateStr == null || endDateStr == null) {
            resp.setStatus(400);  // 400 = Bad Request
            resp.getWriter().write("{\"error\":\"Missing required parameters: type, startDate, endDate\"}");
            return;
        }

        // ---- Generate the report using the ReportService ----

        // Create the ReportService that handles running the database queries
        ReportService reportService = new ReportService();
        // Parse the date strings into LocalDate objects
        LocalDate startDate = LocalDate.parse(startDateStr);
        LocalDate endDate = LocalDate.parse(endDateStr);

        // Start building the JSON response with the report metadata
        JsonObject result = new JsonObject();
        result.addProperty("reportType", reportType);
        result.addProperty("startDate", startDateStr);
        result.addProperty("endDate", endDateStr);

        // Generate the appropriate report based on the type parameter
        if ("occupancy".equalsIgnoreCase(reportType)) {
            // Generate an occupancy report (how full the hotel was)
            List<Map<String, Object>> data = reportService.getOccupancyReport(startDate, endDate);
            // Convert the report data to JSON and add it to the response
            result.add("data", gson.toJsonTree(data));
        } else if ("revenue".equalsIgnoreCase(reportType)) {
            // Generate a revenue report (how much money was earned)
            List<Map<String, Object>> data = reportService.getRevenueReport(startDate, endDate);
            // Convert the report data to JSON and add it to the response
            result.add("data", gson.toJsonTree(data));
        } else {
            // If an invalid report type was given, return a 400 Bad Request error
            resp.setStatus(400);
            resp.getWriter().write("{\"error\":\"Invalid report type. Use 'occupancy' or 'revenue'\"}");
            return;
        }

        // Write the complete report JSON response to the browser
        resp.getWriter().write(result.toString());
    }
}
